### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by EvanMarkHopkins** [EvanMarkHopkins/spagett#2]
Before we get started, it might help to decide on a consistent coding style. Here's a couple I found: 

* https://github.com/feross/standard
* https://github.com/hapijs/contrib/blob/master/Style.md

Any preferences? Other ideas?

**Comment by zrgaines** [comment]
I'm down with using standard

**Comment by EvanMarkHopkins** [comment]
yeah, that one is probably the best, considering it also has a build in tool for checking your code

**Comment by EvanMarkHopkins** [comment]
This does mean you have to configure your editor to use spaces instead of tabs.
